name: Build

on:
  workflow_run:
    workflows:
      - "Tests"
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/base_ci_workflow.yaml
    with:
      command: build
