name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/base_ci_workflow.yaml
    with:
      command: lint
