name: Lint

on:
  - push
  - pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/base_setup_workflow.yaml

  lint:
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Run Linting
        run: make lint
