name: Lint

on: [ push ]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/base_setup_workflow.yml

    steps:
      - name: Run Linting
        run: make lint
