name: Publish

on:
  workflow_run:
    workflows:
      - "Build"
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  publish:
    name: Publish
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/base_ci_workflow.yaml
    with:
      command: publish
    secrets:
      pypi_token: ${{ secrets.PYPI_TOKEN }}
