name: Tests

on:
  workflow_run:
    workflows:
      - "Lint"
    types:
      - completed

permissions:
  contents: read
  pull-requests: read

jobs:
  unittests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/base_ci_workflow.yaml
    with:
      command: test-cover
